//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class UserProfile
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Gender { get; set; }
      
        public string SecondaryEmailAddres { get; set; }
        public string CountryCode { get; set; }
        [Required]
        public string PhoneNumber { get; set; }
        public string ProfilePicture { get; set; }
        [Required]
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string State { get; set; }
        [Required]
        public string ZipCode { get; set; }
        [Required]
        public string Country { get; set; }
        [Required]
        public string University { get; set; }
        [Required]
        public string College { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ReferenceData ReferenceData { get; set; }
        public virtual User User { get; set; }
        
        public string SelectGender { get; set; }
       
        public string FristName { get; set; }
       
        public string LastName { get; set; }
       
        public HttpPostedFileBase DisplayFile { get; set; }


    }
}
